# Generated by Django 6.0 on 2025-12-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_generatedrag_finished_at_generatedrag_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedrag',
            name='content',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='generatedrag',
            name='lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedrag',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
    ]
