# Generated by Django 6.0 on 2025-12-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_generatedrag_content_generatedrag_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedrag',
            name='errors',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
