# Generated by Django 6.0 on 2025-12-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_generatedrag_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedrag',
            name='page_count',
        ),
    ]
