# Generated by Django 6.0 on 2025-12-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_generatedrag_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedrag',
            name='content',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
